---

keep_auth_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30396164366365333366656339323937396561356264653062623262336539653464623038356338
          3162313936316632343062636438663563373463643633640a623435613165613136333231303662
          31393238393538316466306163646564643237376466333863353263613639663737303662666566
          3964306132313662620a313734313462353134323062303737393237313263346566316135376435
          3632
